### ISSUE TITLE
[Paper] State of the field 

### ISSUE THREAD

**Issue by isdanni** [TRI-AMDD/GMP-featurizer#2]
Quoting the [summary](https://github.com/TRI-AMDD/GMP-featurizer/blob/JOSS/paper.md#summary) section of the paper: " Starting from the GMP feature computation module from AmpTorch [@amptorch], the capability of GMP-Featurizer has since been greatly improved, including its accuracy and efficiency, as well as the ability to parallelize on different cores, even machines. Moreover, this python package only has very few dependencies that are all standard python libraries, plus cffi for C++ code interfacing and Ray [@Ray] for parallelization, making it lightweight and robust. "

Would you mind explaining a bit more regarding the **accuracy** and **efficiency** of GMP-featurizer compared to the GMP feature computation module from AmpTorch? For example, computing speedup by *.*x times.
 
This is to meet the following review criteria:
-  State of the field: Do the authors describe how this software compares to other commonly-used packages?

**Comment by isdanni** [comment]
linking https://github.com/openjournals/joss-reviews/issues/5476 to track review progress.

**Comment by RayLei-TRI** [comment]
@isdanni That you very much for pointing it out! I also think we need some explanation for this claim. 

The difference is mainly caused by the adaptive neighboring atom identification scheme v.s. the old hard distance cutoff scheme as implemented in AmpTorch. I have added the following text to the paper to explain it, please let me know what you think. 

"""
....the GMP-featurizer package, unlike common local chemical environment featurization schemes (including the original implementation of GMP in AmpTorch), eliminates the need to define a hard distance cutoff for determining the local environment to be featurized. Instead, users simply need to state the desired accuracy of the features. GMP-featurizer then autonomously identifies neighboring atoms that make meaningful contributions to each GMP feature relative to the set accuracy level, and computes the features. This change is significant because GMP featurizes the underlying electron density of chemical systems, which can greatly vary between elements and hence influence the GMP features differently. For instance, a distant Mercury atom may have a larger impact on GMP features than a closer Hydrogen atom. Additionally, different GMP features respond differently to changes in atomic positions, making a universal cutoff inefficient and potentially leading to a lot of unnecessary computations (when the cutoff is set too high) or inaccurate features (when set too low). GMP-featurizer's new adaptive scheme circumvents these issues. It not only enhances efficiency and precision but also simplifies the user experience.
"""

However, as you can see, direct comparison in terms of speed-up is hard, as it depends on a lot of things from the set of features, intended accuracy, available elements, etc. in *extreme* case, this change leads to >10x shorter computation time, but of couse we don't always get that kind of speed up.

**Comment by isdanni** [comment]
Thanks! This explanation is exactly what I was looking for.
